name: GEMS3K

channels:
  - conda-forge

dependencies:
  - compilers
  - cmake>=3.16
  - ninja
  - git
  - ccache
  - python>=3.10
  - pip
  - pytest
  - pybind11
  - nlohmann_json
  - thermofun>=0.5.4
