name: GEMS3K

channels:
  - conda-forge
  - defaults

dependencies:
  - cmake
  - git
  - gcc_linux-64  # [linux] 
  - gxx_linux-64  # [linux] 
  - sysroot_linux-64 # [linux] 
  - make  # [unix]
  - ninja
  - python>=3.10
  - pip
  - pytest
  - pybind11
  - nlohmann_json
  - thermofun>=0.5.4
