GeoSys-ST: Source Terms ------------------------------------------------
#SOURCE_TERM
 $PCS_TYPE
  GROUNDWATER_FLOW
 $PRIMARY_VARIABLE 
  HEAD
 $GEO_TYPE
  POLYLINE INLET_1
 $DIS_TYPE
 CONSTANT   5.7143e-10 //  unit length value, do not normalize it //
#SOURCE_TERM
 $PCS_TYPE
  GROUNDWATER_FLOW
 $PRIMARY_VARIABLE 
  HEAD
 $GEO_TYPE
  POLYLINE INLET_2
 $DIS_TYPE
  CONSTANT  11.429e-10 //  unit length value, do not normalize it //
#STOP

