#find_package(ZeroMQ REQUIRED)
#find_library(ZEROMQ_LIB zeromq)
#if(NOT ZEROMQ_LIB)
#  message(FATAL_ERROR "zeromq library not found")
#endif()

find_package(ThermoFun REQUIRED)
if(NOT ThermoFun_FOUND)
  message(FATAL_ERROR "ThermoFun library not found")
else()
  message(STATUS "Found ThermoFun v${ThermoFun_VERSION}")
endif()
